adjective_1 = input("Give me an adjective? ")
verb_1 = input("Give me an verb? ")
plural_1 = input("Giv me an plural? ")
adjective_2 = input("Give me an adjective? ")
verb_2 = input("Give me an verb? ")
plural_2 = input ("Give me an plural?")
adjective_3 = input("Give me an adjective? ")
verb_3 = input("Give me an verb? ")
plural_3 = input("Give me an plural? ")
adjective_4 = input("Give me an adjective?")

print("The monster under my bed is  %s," % adjective_1)
print("he %s me" % verb_1)
print("Then more %s appear." % plural_1)
print("There was a %s monster." % adjective_2)
print("The blue monster was %s food." % verb_2)
print("The blue monsters was making %s for his family." % plural_2)
print("There was a %s monster." % adjective_3)
print("The red monster became %s." % verb_3)
print("Then the %s stared to help." % plural_3)
print("All the monsters got even more %s." % adjective_4)